# Generated by Django 4.1.7 on 2023-03-11 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('M', 'Material'), ('S', 'Serviço')], max_length=1)),
                ('descricao', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonativoMaterialOuServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_abreviado', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('unidade', models.CharField(blank=True, choices=[('un', 'Unidade'), ('p', 'Par'), ('kg', 'Quilo'), ('l', 'Litro'), ('m', 'Metro'), ('m2', 'Metro quadrado'), ('s', 'Serviço')], max_length=3, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaEntidade',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaComunidade',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.empresaentidade')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.donativomaterialouservico')),
            ],
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.endereco'),
        ),
        migrations.CreateModel(
            name='EmpresaComunidade',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.endereco')),
            ],
        ),
    ]
