# Generated by Django 4.1.7 on 2023-03-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0002_categoria_donativomaterialouservico_empresaentidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanciamaterial',
            options={'permissions': [('pode_criar_atualizar_material_servico', 'Cria/Atualiza Necessidade')]},
        ),
        migrations.RemoveField(
            model_name='donativomaterialouservico',
            name='nome_abreviado',
        ),
    ]
