# Generated by Django 4.1.7 on 2023-03-12 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0003_alter_instanciamaterial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresacomunidade',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresacomunidade',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='empresaentidade',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoacomunidade',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoacomunidade',
            name='endereco',
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empresaentidade',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.AddField(
            model_name='empresacomunidade',
            name='comunidade_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='empresacomunidade_set', to='appdoacoes.comunidade'),
        ),
        migrations.AddField(
            model_name='pessoacomunidade',
            name='comunidade_ptr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='pessoacomunidade_set', to='appdoacoes.comunidade'),
        ),
    ]
