# Generated by Django 4.1.7 on 2023-03-12 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0004_comunidade_remove_empresacomunidade_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacomunidade',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 digitos')]),
        ),
        migrations.AlterField(
            model_name='empresaentidade',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 digitos')]),
        ),
        migrations.AlterField(
            model_name='pessoacomunidade',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 digitos')]),
        ),
    ]
