# Generated by Django 4.1.7 on 2023-03-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0005_alter_empresacomunidade_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': [('pode_criar_atualizar_categoria', 'Cria/Atualiza categoria'), ('pode_deletar_categoria', 'Deleta categoria')]},
        ),
        migrations.AlterModelOptions(
            name='donativomaterialouservico',
            options={'permissions': [('pode_criar_atualizar_donativo', 'Cria/Atualiza Donativo'), ('pode_deletar_donativo', 'Deleta Donativo')]},
        ),
        migrations.AlterModelOptions(
            name='instanciamaterial',
            options={},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Material', 'Material'), ('S', 'Serviço')], max_length=8),
        ),
    ]
