# Generated by Django 4.1.7 on 2023-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0006_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('Material', 'Material'), ('Serviço', 'Serviço')], max_length=8),
        ),
    ]
