# Generated by Django 4.1.7 on 2023-03-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0008_alter_empresaentidade_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonativoMaterialOuServico',
            new_name='Donativo',
        ),
        migrations.RenameModel(
            old_name='InstanciaMaterial',
            new_name='InstanciaDonativo',
        ),
        migrations.AlterModelOptions(
            name='empresaentidade',
            options={'permissions': [('pode_criar_atualizar_entidade', 'Cria/Atualiza Entidade'), ('pode_deletar_entidade', 'Deleta Entidade')]},
        ),
    ]
