# Generated by Django 4.1.7 on 2023-03-15 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0009_rename_donativomaterialouservico_donativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appdoacoes.comunidade', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='entidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appdoacoes.empresaentidade', verbose_name='Entidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_de_conta',
            field=models.CharField(choices=[('comunidade', 'Comunidade'), ('entidade', 'Entidade')], default='comunidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresaentidade',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
