# Generated by Django 4.1.7 on 2023-03-15 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0010_user_comunidade_user_entidade_user_tipo_de_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comunidade',
        ),
        migrations.AddField(
            model_name='user',
            name='comunidade_pf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appdoacoes.pessoacomunidade', verbose_name='Comunidade PF'),
        ),
        migrations.AddField(
            model_name='user',
            name='comunidade_pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appdoacoes.empresacomunidade', verbose_name='Comunidade PJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_de_conta',
            field=models.CharField(choices=[('comunidade-PF', 'Comunidade PF'), ('comunidade-PJ', 'Comunidade PJ'), ('entidade', 'Entidade')], max_length=20),
        ),
    ]
