# Generated by Django 4.1.7 on 2023-03-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0011_remove_user_comunidade_user_comunidade_pf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanciadonativo',
            options={'permissions': [('pode_criar_atualizar_necessidade', 'Cria/Atualiza necessidade'), ('pode_deletar_necessidade', 'Deleta necessidade')]},
        ),
        migrations.RemoveField(
            model_name='instanciadonativo',
            name='material',
        ),
        migrations.AddField(
            model_name='instanciadonativo',
            name='donativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appdoacoes.donativo'),
        ),
    ]
