# Generated by Django 4.1.7 on 2023-03-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0013_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='detalhes',
            field=models.TextField(null=True),
        ),
    ]
