# Generated by Django 4.1.7 on 2023-03-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoacoes', '0014_alter_perfilusuario_detalhes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
