# Generated by Django 4.1.2 on 2023-02-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite um genereo. Ex: Ficção científica', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sumario', models.TextField(help_text='Digite uma descrição resumida do livro', max_length=1000)),
                ('isbn', models.CharField(help_text='código de 13 caracteres ISBN - href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.ManyToManyField(help_text='Selecione um genero para este livro', to='catalog.genero')),
            ],
        ),
    ]
