# Generated by Django 4.1.2 on 2023-02-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_instancialivro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancialivro',
            options={'ordering': ['data_devolucao'], 'permissions': (('pode_registrar_devolucao', 'Devolve livro'), ('pode_renovar_livro', 'Renova livro'))},
        ),
    ]
