# Generated by Django 4.1.2 on 2023-02-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_instancialivro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome', 'sobrenome'], 'permissions': [('pode_criar_atualizar_autor', 'Cria/Atualiza autor'), ('pode_deletar_autor', 'Deleta autor')]},
        ),
    ]
