# Generated by Django 4.1.2 on 2023-02-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'permissions': [('pode_criar_atualizar_livro', 'Cria/Atualiza Livro'), ('pode_deletar_livro', 'Deleta livro')]},
        ),
    ]
